name: auto-tests

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
          cache: 'pip'
          cache-dependency-path: 'poetry.lock'
          cache-subdir: ${{ runner.os }}-python-${{ matrix.python-version }}
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -U poetry
          poetry config virtualenvs.in-project true
          poetry install

      - name: Run tests
        run: poetry run pytest --cov=gendiff --cov-report=xml --cov-report=term tests/

      - name: Download Code Climate Reporter
        run: |
          curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
          chmod +x ./cc-test-reporter

      - name: Prepare coverage report
        run: ./cc-test-reporter format-coverage --output coverage/codeclimate.json

      - name: Upload coverage to Code Climate
        run: which cc-test-reporter && $(which cc-test-reporter) upload-coverage
